#!/usr/bin/env bash
set -euo pipefail

MYSQL_HOST="${ALGOFORGE_DB_HOST:-127.0.0.1}"
MYSQL_PORT="${ALGOFORGE_DB_PORT:-3306}"
MYSQL_ROOT_USER="${ALGOFORGE_DB_ROOT_USER:-root}"
MYSQL_ROOT_PASSWORD="${ALGOFORGE_DB_ROOT_PASSWORD:-}"
MYSQL_APP_USER="${ALGOFORGE_DB_USER:-algoforge}"
MYSQL_APP_PASSWORD="${ALGOFORGE_DB_PASSWORD:-algoforge}"
MYSQL_APP_DATABASE="${ALGOFORGE_DB_NAME:-algoforge}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

ROOT_ARGS=(-h "${MYSQL_HOST}" -P "${MYSQL_PORT}" -u "${MYSQL_ROOT_USER}")
if [[ -n "${MYSQL_ROOT_PASSWORD}" ]]; then
  ROOT_ARGS+=("-p${MYSQL_ROOT_PASSWORD}")
fi

mysql "${ROOT_ARGS[@]}" <<SQL
CREATE DATABASE IF NOT EXISTS ${MYSQL_APP_DATABASE}
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS '${MYSQL_APP_USER}'@'%' IDENTIFIED BY '${MYSQL_APP_PASSWORD}';
CREATE USER IF NOT EXISTS '${MYSQL_APP_USER}'@'localhost' IDENTIFIED BY '${MYSQL_APP_PASSWORD}';
GRANT ALL PRIVILEGES ON ${MYSQL_APP_DATABASE}.* TO '${MYSQL_APP_USER}'@'%';
GRANT ALL PRIVILEGES ON ${MYSQL_APP_DATABASE}.* TO '${MYSQL_APP_USER}'@'localhost';
FLUSH PRIVILEGES;
SQL

mysql "${ROOT_ARGS[@]}" < "${BACKEND_DIR}/data/db_schema.sql"
mysql "${ROOT_ARGS[@]}" < "${BACKEND_DIR}/data/db_seed.sql"

echo "MySQL schema and seed data are ready for database '${MYSQL_APP_DATABASE}'."
